[project]
name = "scrappers"
version = "0.1.0"
description = "Scrappers peraturan perundang-undangan from JDIH Sekretariat Negara"
readme = "README.md"
authors = [{ name = "Sukirno", email = "mblonyox@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "click>=8.4.2",
    "easyocr>=1.7.2",
    "ipykernel>=7.3.0",
    "kreuzberg>=4.10.2",
    "marker-pdf>=2.0.0",
    "pymupdf>=1.28.2",
    "requests>=2.34.2",
    "tqdm>=4.70.0",
    "typer>=0.27.1",
]
